syntax = "proto3";

package app_center.v1.runtime_resolution;

option go_package = "github.com/TokenTeam/iwut-api-proto/gen/go/app_center/v1/runtime_resolution;runtime_resolution";

enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  ERROR_REASON_INVALID_AUTHENTICATED_USER = 1;
  ERROR_REASON_INVALID_APPLICATION_ID = 2;
  ERROR_REASON_INVALID_HOST_RPC_API_MAJOR = 3;
  ERROR_REASON_INVALID_HOST_CAPABILITIES = 4;
  ERROR_REASON_APPLICATION_NOT_FOUND = 5;
  ERROR_REASON_APPLICATION_LAUNCH_TARGET_UNAVAILABLE = 6;
  ERROR_REASON_APPLICATION_RUNTIME_STATE_INCONSISTENT = 7;
  ERROR_REASON_INTERNAL = 8;
  ERROR_REASON_INVALID_RESOLVE_LAUNCH_TARGET_REQUEST = 9;
}
