syntax = "proto3";
package app_center.v1.tester_membership;
option go_package = "github.com/TokenTeam/iwut-api-proto/gen/go/app_center/v1/tester_membership;testermembership";
enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  ERROR_REASON_AUTHENTICATED_USER_REQUIRED = 1;
  ERROR_REASON_INVALID_AUTHENTICATED_USER = 2;
  ERROR_REASON_INVALID_TESTER_JOIN_LINK_ID = 3;
  ERROR_REASON_INVALID_TESTER_JOIN_SECRET = 4;
  ERROR_REASON_TESTER_JOIN_LINK_INVALID = 5;
  ERROR_REASON_APPLICATION_TESTER_LIMIT_REACHED = 6;
  ERROR_REASON_INTERNAL = 7;
  ERROR_REASON_DEVELOPER_IDENTITY_REQUIRED = 8;
  ERROR_REASON_INVALID_DEVELOPER_IDENTITY = 9;
  ERROR_REASON_DEVELOPER_APPROVAL_REQUIRED = 10;
  ERROR_REASON_INVALID_APPLICATION_ID = 11;
  ERROR_REASON_INVALID_TESTER_MEMBERSHIP_ID = 12;
  ERROR_REASON_APPLICATION_ADMIN_REQUIRED = 13;
  ERROR_REASON_APPLICATION_TESTER_MEMBERSHIP_NOT_FOUND = 14;
  ERROR_REASON_APPLICATION_TESTER_STATE_INCONSISTENT = 15;
  ERROR_REASON_INVALID_REMOVE_TESTER_REQUEST = 16;
}
