syntax = "proto3";

package app_center.v1.application_catalog;

option go_package = "github.com/TokenTeam/iwut-api-proto/gen/go/app_center/v1/application_catalog;applicationcatalog";

enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  ERROR_REASON_INVALID_AUTHENTICATED_USER = 1;
  ERROR_REASON_INVALID_APPLICATION_ID = 2;
  ERROR_REASON_INVALID_HOST_RPC_API_MAJOR = 3;
  ERROR_REASON_INVALID_HOST_CAPABILITIES = 4;
  ERROR_REASON_INVALID_PAGE_SIZE = 5;
  ERROR_REASON_INVALID_PAGE_TOKEN = 6;
  ERROR_REASON_PUBLIC_APPLICATION_NOT_FOUND = 7;
  ERROR_REASON_APPLICATION_CATALOG_STATE_INCONSISTENT = 8;
  ERROR_REASON_INTERNAL = 9;
  ERROR_REASON_INVALID_APPLICATION_CATALOG_REQUEST = 10;
}
