syntax = "proto3";

package app_center.v1.application_operations;

option go_package = "github.com/TokenTeam/iwut-api-proto/gen/go/app_center/v1/application_operations;applicationoperations";

enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  ERROR_REASON_USER_IDENTITY_REQUIRED = 1;
  ERROR_REASON_INVALID_USER_IDENTITY = 2;
  ERROR_REASON_APPLICATION_OPERATION_FORBIDDEN = 3;
  ERROR_REASON_INVALID_APPLICATION_ID = 4;
  ERROR_REASON_INVALID_LIFECYCLE_REVISION = 5;
  ERROR_REASON_INVALID_PLATFORM_AVAILABILITY_REVISION = 6;
  ERROR_REASON_INVALID_APPLICATION_OPERATION_REASON = 7;
  ERROR_REASON_APPLICATION_NOT_FOUND = 8;
  ERROR_REASON_APPLICATION_AVAILABILITY_CONFLICT = 9;
  ERROR_REASON_APPLICATION_NOT_ACTIVE = 10;
  ERROR_REASON_APPLICATION_OPERATION_STATE_INCONSISTENT = 11;
  ERROR_REASON_APPLICATION_OPERATION_UNAVAILABLE = 12;
  ERROR_REASON_INTERNAL = 13;
}
