syntax = "proto3";
package app_center.v1.application_profile_revision;
option go_package = "github.com/TokenTeam/iwut-api-proto/gen/go/app_center/v1/application_profile_revision;applicationprofilerevision";
enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  ERROR_REASON_INVALID_APPLICATION_ID = 1;
  ERROR_REASON_INVALID_APPLICATION_DISPLAY_NAME = 2;
  ERROR_REASON_INVALID_APPLICATION_DESCRIPTION = 3;
  ERROR_REASON_INVALID_APPLICATION_ICON = 4;
  ERROR_REASON_DEVELOPER_IDENTITY_REQUIRED = 5;
  ERROR_REASON_INVALID_DEVELOPER_IDENTITY = 6;
  ERROR_REASON_DEVELOPER_APPROVAL_REQUIRED = 7;
  ERROR_REASON_APPLICATION_NOT_FOUND = 8;
  ERROR_REASON_APPLICATION_ADMIN_REQUIRED = 9;
  ERROR_REASON_APPLICATION_PROFILE_WORK_REVISION_ALREADY_EXISTS = 10;
  ERROR_REASON_APPLICATION_PROFILE_STATE_INCONSISTENT = 11;
  ERROR_REASON_INVALID_CREATE_APPLICATION_PROFILE_REVISION_REQUEST = 12;
  ERROR_REASON_INTERNAL = 13;
}
